# Generated by Django 3.2.5 on 2021-07-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20210724_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2021-04-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='orgainser_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
