# Generated by Django 3.2.5 on 2021-07-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20210724_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='orgainser_email',
        ),
    ]
