# Generated by Django 3.2.5 on 2021-07-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_remove_meetup_orgainser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
    ]
