# Generated by Django 3.2.5 on 2021-07-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_remove_meetup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default='2021-04-21'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='orgainser_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
